# Generated by Django 2.2.4 on 2020-01-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_auto_20200126_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morder',
            old_name='Mname',
            new_name='MName',
        ),
        migrations.RenameField(
            model_name='morder',
            old_name='Msupplier',
            new_name='MsupplierName',
        ),
    ]
