# Generated by Django 3.0.2 on 2020-01-24 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0004_auto_20200124_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gsm',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 17, 48, 43, 716720)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 17, 48, 43, 701099)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 17, 48, 43, 716720)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
