# Generated by Django 3.0.2 on 2020-01-24 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0005_auto_20200124_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 17, 54, 24, 775211)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 17, 54, 24, 767209)),
        ),
        migrations.AlterField(
            model_name='order',
            name='gsm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 17, 54, 24, 771217)),
        ),
    ]
