# Generated by Django 3.0.2 on 2020-01-24 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0006_auto_20200124_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 18, 32, 16, 654064)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 18, 32, 16, 654064)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 18, 32, 16, 654064)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
