# Generated by Django 3.0.2 on 2020-01-25 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0008_auto_20200124_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 12, 42, 53, 235185)),
        ),
        migrations.AlterField(
            model_name='morder',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 12, 42, 53, 235185)),
        ),
        migrations.AlterField(
            model_name='mpayment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 12, 42, 53, 235185)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 12, 42, 53, 235185)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 25, 12, 42, 53, 235185)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='Mobile',
            field=models.IntegerField(),
        ),
    ]
