# Generated by Django 2.2.4 on 2020-01-26 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0010_auto_20200126_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
