# Generated by Django 2.2.4 on 2020-01-26 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morder',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='morder',
            name='Quantity',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mpayment',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
