# Generated by Django 3.0.2 on 2020-01-23 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=20000)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Company', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.CharField(max_length=12)),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2020, 1, 23, 13, 16, 2, 226373))),
                ('paidIn', models.CharField(choices=[('Cash', 'Cash'), ('cheque', 'Cheque')], default='Cash', max_length=10)),
                ('credit', models.IntegerField(default=0)),
                ('Comment', models.TextField(blank=True)),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderName', models.CharField(max_length=30)),
                ('Date', models.DateField(default=datetime.datetime(2020, 1, 23, 13, 16, 2, 224372))),
                ('document', models.FileField(upload_to='documents/')),
                ('Size', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Comment', models.TextField(blank=True)),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2020, 1, 23, 13, 16, 2, 228375))),
                ('debit', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('Amount', models.IntegerField(blank=True, default=0)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.Order')),
                ('paymentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.Payment')),
                ('supplierName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.supplier')),
            ],
        ),
    ]
