# Generated by Django 3.0.2 on 2020-01-24 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0003_auto_20200124_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 13, 51, 51, 955321)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 13, 51, 51, 951317)),
        ),
        migrations.AlterField(
            model_name='order',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 13, 51, 51, 955321)),
        ),
    ]
