# Generated by Django 3.0.2 on 2020-01-24 13:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0007_auto_20200124_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Company', models.CharField(max_length=30)),
                ('Mobile', models.CharField(max_length=12)),
                ('Address', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 18, 46, 27, 648743)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 18, 46, 27, 648743)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 18, 46, 27, 648743)),
        ),
        migrations.CreateModel(
            name='MPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.datetime(2020, 1, 24, 18, 46, 27, 648743))),
                ('paidBy', models.CharField(choices=[('Cash', 'Cash'), ('cheque', 'Cheque'), ('Online', 'Online')], default='Cash', max_length=10)),
                ('Amount', models.IntegerField(default=0)),
                ('Comment', models.TextField(blank=True)),
                ('Msupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.Msupplier')),
            ],
        ),
        migrations.CreateModel(
            name='MOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mname', models.CharField(max_length=30)),
                ('Date', models.DateField(default=datetime.datetime(2020, 1, 24, 18, 46, 27, 648743))),
                ('Size', models.CharField(blank=True, max_length=30)),
                ('gsm', models.IntegerField(blank=True)),
                ('Quantity', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Comment', models.TextField(blank=True)),
                ('Msupplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printapp.Msupplier')),
            ],
        ),
    ]
