# Generated by Django 2.2.4 on 2020-01-26 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0009_auto_20200125_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpayment',
            name='Msupplier',
        ),
        migrations.AlterField(
            model_name='balance',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 10, 51, 42, 790932)),
        ),
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 10, 51, 42, 790932)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=datetime.datetime(2020, 1, 26, 10, 51, 42, 790932)),
        ),
        migrations.DeleteModel(
            name='MOrder',
        ),
        migrations.DeleteModel(
            name='MPayment',
        ),
        migrations.DeleteModel(
            name='Msupplier',
        ),
    ]
